[project]
name = "booth"
version = "0.0.1"
description = "A REST API Python microservice which allows users to browse a product catalogue and which automatically updates prices from the offer service."
dependencies = [
	"flask",
]
